#info:
#  component: Zuul Server
  
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

zuul:
  routes:
    student-service:
      path: /students/**
      serviceId: student-service
      strip-prefix: false

server:
  port: 8085


spring:
  application:
    name: gateway
